### ISSUE TITLE
Issue related with template selector positioning

### ISSUE THREAD

**Issue by benatespina** [LIN3S/CMSKernel#26]
This solves an issue related with template selector.

```scss
// _template-selector.scss

$template-selector-transition-duration: .4s;
$template-selector-transition-type: ease-in-out;
$template-selector-margin-bottom: 15px;

.template-selector__templates {
  overflow: hidden;
}

.template-selector__template {
  height: 0;
  margin-bottom: 0;
  opacity: 0;
  overflow: hidden;
  pointer-events: none;
  transition: opacity $template-selector-transition-duration $template-selector-transition-type;
}

.template-selector__template--selected {
  display: block;
  height: 100%;
  margin-bottom: $template-selector-margin-bottom;
  opacity: 1;
  pointer-events: auto;
}
```
